# Generated by Django 6.0.4 on 2026-04-18 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('Name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)])),
                ('DirectorID', models.ManyToManyField(related_name='movies', to='intersecter.directors')),
                ('GenreID', models.ManyToManyField(related_name='movies', to='intersecter.genres')),
            ],
        ),
        migrations.CreateModel(
            name='LetterboxdUsers',
            fields=[
                ('NickName', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('MovieID', models.ManyToManyField(blank=True, related_name='users', to='intersecter.movies')),
            ],
        ),
    ]
